#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift( File.expand_path( "../lib", __dir__ ) )
require "carson"

exit Carson::CLI.start(
	argv: ARGV.dup,
	repo_root: Dir.pwd,
	tool_root: File.expand_path( "..", __dir__ ),
	out: $stdout,
	err: $stderr
)
